import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Briefcase, FileText, Send, Users } from 'lucide-react';
import { Alert } from '../../components/feedback/Alert';
import { LoadingSpinner } from '../../components/feedback/LoadingSpinner';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card';
import { getAdminAnalyticsApi, getAdminUsersApi, getCandidateAnalyticsApi, getRecruiterAnalyticsApi } from '../../services/api';
import { useAuthStore } from '../../store/authStore';
import { User } from '../../types/auth';
import { AdminAnalytics, CandidateAnalytics, RecruiterAnalytics } from '../../types/platform';

const Metric = ({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) => <Card><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold text-slate-900">{value}</p></div><div className="rounded-xl bg-teal-50 p-3 text-teal-700">{icon}</div></CardContent></Card>;
const Stages = ({ values }: { values: Record<string, number> }) => <Card><CardHeader><CardTitle>Pipeline distribution</CardTitle></CardHeader><CardContent>{Object.keys(values).length ? <div className="space-y-3">{Object.entries(values).map(([stage, count]) => <div key={stage} className="flex items-center justify-between border-b border-slate-100 pb-2 text-sm"><span className="capitalize text-slate-600">{stage}</span><strong>{count}</strong></div>)}</div> : <p className="text-sm text-slate-500">No application activity yet.</p>}</CardContent></Card>;

export const OverviewPage = () => {
  const { user } = useAuthStore(); const [data, setData] = useState<CandidateAnalytics | RecruiterAnalytics | AdminAnalytics>(); const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { const load = async () => { if (user?.role === 'candidate') setData(await getCandidateAnalyticsApi()); else if (user?.role === 'recruiter') setData(await getRecruiterAnalyticsApi()); else { setData(await getAdminAnalyticsApi()); setUsers((await getAdminUsersApi()).users); } }; load().catch((err: Error) => setError(err.message)).finally(() => setLoading(false)); }, [user?.role]);
  if (loading) return <div className="py-20"><LoadingSpinner label="Loading your dashboard…" /></div>;
  if (error || !data) return <Alert variant="error">{error || 'Dashboard data is unavailable.'}</Alert>;
  if (user?.role === 'candidate') { const value = data as CandidateAnalytics; return <section className="space-y-6"><header><p className="text-sm font-semibold text-teal-600">Candidate dashboard</p><h1 className="text-3xl font-bold text-slate-900">Welcome back, {user.fullName}</h1></header><div className="grid gap-4 sm:grid-cols-3"><Metric label="Applications" value={value.totalApplications} icon={<Send />} /><Metric label="Active applications" value={value.activeApplications} icon={<Briefcase />} /><Metric label="Profile skills" value={value.profile.skillsCount} icon={<FileText />} /></div>{!value.profile.hasResume && <Alert variant="warning">Your profile has no resume. <Link to="/candidate/profile" className="font-semibold underline">Upload one now</Link>.</Alert>}<Stages values={value.byStage} /></section>; }
  if (user?.role === 'recruiter') { const value = data as RecruiterAnalytics; return <section className="space-y-6"><header><p className="text-sm font-semibold text-teal-600">Recruiter dashboard</p><h1 className="text-3xl font-bold text-slate-900">Hiring overview</h1></header><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Total jobs" value={value.totalJobs} icon={<Briefcase />} /><Metric label="Published jobs" value={value.publishedJobs} icon={<FileText />} /><Metric label="Draft jobs" value={value.draftJobs} icon={<FileText />} /><Metric label="Applicants" value={value.totalApplicants} icon={<Users />} /></div><Stages values={value.byStage} /></section>; }
  const value = data as AdminAnalytics; return <section className="space-y-6"><header><p className="text-sm font-semibold text-teal-600">Administration</p><h1 className="text-3xl font-bold text-slate-900">Platform overview</h1></header><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Users" value={value.users} icon={<Users />} /><Metric label="Candidates" value={value.candidates} icon={<Users />} /><Metric label="Recruiters" value={value.recruiters} icon={<Users />} /><Metric label="Applications" value={value.applications} icon={<Send />} /></div><div className="grid gap-6 lg:grid-cols-2"><Stages values={value.byStage} /><Card><CardHeader><CardTitle>Recent users</CardTitle></CardHeader><CardContent className="space-y-3">{users.slice(0, 10).map((entry) => <div key={entry._id} className="flex justify-between border-b border-slate-100 pb-2 text-sm"><span><strong>{entry.fullName}</strong><span className="ml-2 text-slate-400">{entry.email}</span></span><span className="capitalize text-slate-500">{entry.role}</span></div>)}</CardContent></Card></div></section>;
};
