import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { BriefcaseBusiness, Plus, Users, Pencil, XCircle, Send } from 'lucide-react';
import { getRecruiterJobsApi, updateJobStatusApi } from '../../services/api';
import { Job } from '../../types/jobs';
import { Card, CardContent } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { LoadingSpinner } from '../../components/feedback/LoadingSpinner';

const badge: Record<Job['status'], string> = { draft: 'bg-slate-100 text-slate-700', published: 'bg-emerald-50 text-emerald-700', closed: 'bg-rose-50 text-rose-700' };

export const RecruiterJobsPage = () => {
  const [jobs, setJobs] = useState<Job[]>([]); const [status, setStatus] = useState<Job['status'] | ''>(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { try { setLoading(true); setJobs((await getRecruiterJobsApi(status ? { status } : {})).jobs); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load jobs.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [status]);
  const setJobStatus = async (id: string, next: Job['status']) => { try { const job = await updateJobStatusApi(id, next); setJobs((items) => items.map((item) => item._id === id ? job : item)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update status.'); } };
  return <section className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-teal-600">Recruiter workspace</p><h1 className="text-3xl font-bold text-slate-900">Job requisitions</h1></div><Link to="/recruiter/jobs/new"><Button leftIcon={<Plus className="h-4 w-4" />}>Create job</Button></Link></div>
    <div className="flex gap-2"><select value={status} onChange={(event) => setStatus(event.target.value as Job['status'] | '')} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="closed">Closed</option></select></div>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}
    {loading ? <div className="py-16"><LoadingSpinner label="Loading job requisitions…" /></div> : jobs.length === 0 ? <Card><CardContent className="py-14 text-center text-slate-500">No jobs found. Create a requisition to begin hiring.</CardContent></Card> : <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Job</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Created</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{jobs.map((job) => <tr key={job._id} className="border-t border-slate-100"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{job.title}</p><p className="mt-1 text-xs text-slate-500">{job.location} · {job.employmentType} · {job.applicationCount ?? 0} applicants</p></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${badge[job.status]}`}>{job.status}</span></td><td className="px-5 py-4 text-slate-500">{new Date(job.createdAt).toLocaleDateString()}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Link to={`/recruiter/jobs/${job._id}`}><Button size="sm" variant="ghost" title="View job"><BriefcaseBusiness className="h-4 w-4" /></Button></Link><Link to={`/recruiter/jobs/${job._id}/edit`}><Button size="sm" variant="ghost" title="Edit job"><Pencil className="h-4 w-4" /></Button></Link><Link to={`/recruiter/jobs/${job._id}/applicants`}><Button size="sm" variant="ghost" title="Applicants"><Users className="h-4 w-4" /></Button></Link>{job.status === 'draft' && <Button size="sm" variant="ghost" title="Publish" onClick={() => void setJobStatus(job._id, 'published')}><Send className="h-4 w-4" /></Button>}{job.status === 'published' && <Button size="sm" variant="ghost" title="Close" onClick={() => void setJobStatus(job._id, 'closed')}><XCircle className="h-4 w-4" /></Button>}</div></td></tr>)}</tbody></table></div>}</section>;
};
