import { FormEvent, useEffect, useState } from 'react';
import { Building2 } from 'lucide-react';
import { Alert } from '../../components/feedback/Alert';
import { LoadingSpinner } from '../../components/feedback/LoadingSpinner';
import { Button } from '../../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card';
import { createCompanyApi, getMyCompanyApi } from '../../services/api';
import { CompanySummary } from '../../types/jobs';

export const RecruiterCompanyPage = () => {
  const [company, setCompany] = useState<CompanySummary | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const [form, setForm] = useState({ name: '', description: '', website: '', industry: '', companySize: '11-50' as const, location: '' });
  useEffect(() => { getMyCompanyApi().then(setCompany).catch((err: Error) => setError(err.message)).finally(() => setLoading(false)); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); try { setSaving(true); setError(''); const value = await createCompanyApi(form); setCompany(value); setSuccess('Company workspace created. You can now create job requisitions.'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create company.'); } finally { setSaving(false); } };
  if (loading) return <LoadingSpinner label="Loading company…" />;
  return <section className="mx-auto max-w-3xl space-y-6"><div><p className="text-sm font-semibold text-teal-600">Recruiter setup</p><h1 className="text-3xl font-bold text-slate-900">Company workspace</h1></div>{error && <Alert variant="error">{error}</Alert>}{success && <Alert variant="success">{success}</Alert>}{company ? <Card><CardContent className="p-6"><Building2 className="h-8 w-8 text-teal-600" /><h2 className="mt-3 text-2xl font-bold">{company.name}</h2><p className="mt-2 text-sm text-slate-600">{company.description}</p><div className="mt-4 flex gap-4 text-sm text-slate-500"><span>{company.industry}</span><span>{company.location}</span><span>{company.companySize}</span></div></CardContent></Card> : <Card><CardHeader><CardTitle>Create your company profile</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Company name<input required minLength={2} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1 w-full rounded-lg border p-2.5" /></label><label className="text-sm font-medium">Industry<input required minLength={2} value={form.industry} onChange={(e) => setForm({ ...form, industry: e.target.value })} className="mt-1 w-full rounded-lg border p-2.5" /></label><label className="text-sm font-medium">Location<input required minLength={2} value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} className="mt-1 w-full rounded-lg border p-2.5" /></label><label className="text-sm font-medium">Company size<select value={form.companySize} onChange={(e) => setForm({ ...form, companySize: e.target.value as typeof form.companySize })} className="mt-1 w-full rounded-lg border p-2.5"><option>1-10</option><option>11-50</option><option>51-200</option><option>201-500</option><option>500+</option></select></label></div><label className="block text-sm font-medium">Website<input type="url" value={form.website} onChange={(e) => setForm({ ...form, website: e.target.value })} className="mt-1 w-full rounded-lg border p-2.5" /></label><label className="block text-sm font-medium">Description<textarea required minLength={10} maxLength={2000} rows={5} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1 w-full rounded-lg border p-2.5" /></label><Button type="submit" isLoading={saving}>Create company workspace</Button></form></CardContent></Card>}</section>;
};
